// acpvectors emits cross-implementation test vectors for the acphost
// crypto (X25519 + HKDF + ChaCha20-Poly1305 counter nonces) so the Swift
// client can prove byte-compatibility without a live daemon. Output is
// committed as bento-agent-core/Tests/BentoAgentCoreTests/Fixtures/
// acphost-vectors.json — regenerate with `go run ./cmd/acpvectors` after
// any crypto change.
package main

import (
	"crypto/ecdh"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"

	"golang.org/x/crypto/chacha20poly1305"
	"golang.org/x/crypto/hkdf"
)

type vectors struct {
	Comment      string `json:"comment"`
	DaemonID     string `json:"daemon_id"`
	DeviceID     string `json:"device_id"`
	ClientPriv   string `json:"client_priv_hex"`
	ServerPriv   string `json:"server_priv_hex"`
	ClientPubB64 string `json:"client_pub_b64"`
	ServerPubB64 string `json:"server_pub_b64"`
	SharedHex    string `json:"shared_hex"`
	C2SKeyHex    string `json:"c2s_key_hex"`
	S2CKeyHex    string `json:"s2c_key_hex"`
	// Boxes sealed with the c2s key at counters 0 and 1 (ciphertext||tag).
	Plain0    string `json:"plain0"`
	Box0Hex   string `json:"box0_hex"`
	Plain1    string `json:"plain1"`
	Box1Hex   string `json:"box1_hex"`
	HelloMsg  string `json:"hello_sig_message"`
	WelcomeMs string `json:"welcome_sig_message"`
}

func main() {
	curve := ecdh.X25519()
	clientPriv := mustKey(curve, "202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f")
	serverPriv := mustKey(curve, "404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f")

	shared, err := clientPriv.ECDH(serverPriv.PublicKey())
	if err != nil {
		panic(err)
	}

	daemonID, deviceID := "daemon-fixture", "device-fixture"
	salt := []byte("bento-acp-v1:" + daemonID + ":" + deviceID)
	derive := func(info string) []byte {
		key := make([]byte, 32)
		if _, err := io.ReadFull(hkdf.New(sha256.New, shared, salt, []byte(info)), key); err != nil {
			panic(err)
		}
		return key
	}
	c2s, s2c := derive("c2s"), derive("s2c")

	aead, err := chacha20poly1305.New(c2s)
	if err != nil {
		panic(err)
	}
	seal := func(counter uint64, plaintext string) []byte {
		nonce := make([]byte, 12)
		for i := 0; i < 8; i++ {
			nonce[4+i] = byte(counter >> (8 * i)) // little-endian
		}
		return aead.Seal(nil, nonce, []byte(plaintext), nil)
	}

	v := vectors{
		Comment:      "generated by desktop/cmd/acpvectors — do not edit by hand",
		DaemonID:     daemonID,
		DeviceID:     deviceID,
		ClientPriv:   hex.EncodeToString(clientPriv.Bytes()),
		ServerPriv:   hex.EncodeToString(serverPriv.Bytes()),
		ClientPubB64: base64.StdEncoding.EncodeToString(clientPriv.PublicKey().Bytes()),
		ServerPubB64: base64.StdEncoding.EncodeToString(serverPriv.PublicKey().Bytes()),
		SharedHex:    hex.EncodeToString(shared),
		C2SKeyHex:    hex.EncodeToString(c2s),
		S2CKeyHex:    hex.EncodeToString(s2c),
		Plain0:       "first sealed unit",
		Box0Hex:      hex.EncodeToString(seal(0, "first sealed unit")),
		Plain1:       "second sealed unit",
		Box1Hex:      hex.EncodeToString(seal(1, "second sealed unit")),
		HelloMsg:     fmt.Sprintf("bento-acp-hello:v1:%s:%s:%d:%s", daemonID, deviceID, 1700000000, "EPHPUB"),
		WelcomeMs:    fmt.Sprintf("bento-acp-welcome:v1:%s:%s:%d:%s:%s", daemonID, deviceID, 1700000000, "CEPH", "HEPH"),
	}
	out, _ := json.MarshalIndent(v, "", "  ")
	os.Stdout.Write(append(out, '\n'))
}

func mustKey(curve ecdh.Curve, hexSeed string) *ecdh.PrivateKey {
	raw, err := hex.DecodeString(hexSeed)
	if err != nil {
		panic(err)
	}
	key, err := curve.NewPrivateKey(raw)
	if err != nil {
		panic(err)
	}
	return key
}
