import CryptoKit
import XCTest

@testable import BentoLink

/// Cross-implementation vectors generated by the Go host
/// (desktop/cmd/acpvectors). If these pass, the Swift client's X25519 +
/// HKDF + ChaCha20-Poly1305 + nonce scheme is byte-compatible with the
/// daemon.
final class AcpHostVectorTests: XCTestCase {
    struct Vectors: Codable {
        let daemon_id: String
        let device_id: String
        let client_priv_hex: String
        let server_pub_b64: String
        let shared_hex: String
        let c2s_key_hex: String
        let s2c_key_hex: String
        let plain0: String
        let box0_hex: String
        let plain1: String
        let box1_hex: String
        let hello_sig_message: String
        let welcome_sig_message: String
    }

    private func loadVectors() throws -> Vectors {
        let url = Bundle.module.url(
            forResource: "acphost-vectors", withExtension: "json", subdirectory: "Fixtures")!
        return try JSONDecoder().decode(Vectors.self, from: Data(contentsOf: url))
    }

    private func hexData(_ s: String) -> Data {
        var data = Data()
        var iterator = s.makeIterator()
        while let a = iterator.next(), let b = iterator.next() {
            data.append(UInt8(String([a, b]), radix: 16)!)
        }
        return data
    }

    func testSharedSecretAndDerivedKeysMatchGo() throws {
        let v = try loadVectors()
        let clientPriv = try Curve25519.KeyAgreement.PrivateKey(
            rawRepresentation: hexData(v.client_priv_hex))
        let serverPub = try Curve25519.KeyAgreement.PublicKey(
            rawRepresentation: Data(base64Encoded: v.server_pub_b64)!)
        let shared = try clientPriv.sharedSecretFromKeyAgreement(with: serverPub)
        XCTAssertEqual(
            shared.withUnsafeBytes { Data($0) }, hexData(v.shared_hex),
            "X25519 shared secret mismatch")

        let keys = AcpHostProtocol.deriveKeys(
            shared: shared, daemonID: v.daemon_id, deviceID: v.device_id)
        XCTAssertEqual(
            keys.c2s.withUnsafeBytes { Data($0) }, hexData(v.c2s_key_hex), "c2s key mismatch")
        XCTAssertEqual(
            keys.s2c.withUnsafeBytes { Data($0) }, hexData(v.s2c_key_hex), "s2c key mismatch")
    }

    func testSealMatchesGoBoxes() throws {
        let v = try loadVectors()
        var boxer = AcpBoxer(key: SymmetricKey(data: hexData(v.c2s_key_hex)))
        let box0 = try boxer.seal(Data(v.plain0.utf8))
        XCTAssertEqual(box0, hexData(v.box0_hex), "counter-0 box mismatch")
        let box1 = try boxer.seal(Data(v.plain1.utf8))
        XCTAssertEqual(box1, hexData(v.box1_hex), "counter-1 box mismatch")
    }

    func testOpenGoBoxes() throws {
        let v = try loadVectors()
        var boxer = AcpBoxer(key: SymmetricKey(data: hexData(v.c2s_key_hex)))
        XCTAssertEqual(
            String(data: try boxer.open(hexData(v.box0_hex)), encoding: .utf8), v.plain0)
        XCTAssertEqual(
            String(data: try boxer.open(hexData(v.box1_hex)), encoding: .utf8), v.plain1)
    }

    func testSignatureMessageFormats() throws {
        let v = try loadVectors()
        XCTAssertEqual(
            String(
                data: AcpHostProtocol.helloSigMessage(
                    daemonID: v.daemon_id, deviceID: v.device_id, ts: 1_700_000_000,
                    ephPubB64: "EPHPUB"),
                encoding: .utf8),
            v.hello_sig_message)
        XCTAssertEqual(
            String(
                data: AcpHostProtocol.welcomeSigMessage(
                    daemonID: v.daemon_id, deviceID: v.device_id, ts: 1_700_000_000,
                    clientEphB64: "CEPH", hostEphB64: "HEPH"),
                encoding: .utf8),
            v.welcome_sig_message)
    }

    func testUnitBufferMatchesFraming() throws {
        var buf = AcpUnitBuffer()
        let unit = acpPrefixUnit(Data("hello".utf8))
        XCTAssertEqual(try buf.append(unit.prefix(2)).count, 0)
        let units = try buf.append(unit.suffix(from: unit.index(unit.startIndex, offsetBy: 2)))
        XCTAssertEqual(units.count, 1)
        XCTAssertEqual(String(data: units[0], encoding: .utf8), "hello")
    }

    func testFingerprintFormat() throws {
        // Deterministic key → assert shape and stability.
        let raw = Data(repeating: 7, count: 32)
        let fp = AcpHostProtocol.sshFingerprint(rawEd25519PublicKey: raw)
        XCTAssertTrue(fp.hasPrefix("SHA256:"))
        XCTAssertFalse(fp.hasSuffix("="))
        XCTAssertEqual(fp, AcpHostProtocol.sshFingerprint(rawEd25519PublicKey: raw))
    }
}
